config/routes.rb
Rails.application.routes.draw do
  get '/',  to:'clones#index'
  patch '/clones/:id' => 'clones#update'
  resources :favorites,only: [:create,:destroy]
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :clones do
    collection do
    get  'favorite'
    post 'confirm'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/clone.rb
class Clone < ApplicationRecord
  validates :contents,  presence: true,length:{ maximum: 140 }
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
end

app/models/company.rb
class Company < ApplicationRecord
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :company
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :clone
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,presence:true,length:{ maximum: 30}
  validates :email,presence:true,length:{ maximum: 255},
             format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :password,presence:true,length:{ minimum: 6}
#
  before_save { email.downcase!}
  has_secure_password

  has_many :clones
  has_many :favorites, dependent: :destroy
  has_many :favorite_clones, through: :favorites, source: :clone
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/clones_controller.rb
class ClonesController < ApplicationController
  before_action :set_clone, only: [:show,:edit,:update,:destroy]
  before_action :logged_in_user, only: [:new,:edit,:show]

  def index
    @clones = Clone.all
  end

  def new
    @clone = Clone.new
  end

  def show
    @favorite = current_user.favorites.find_by(clone_id: @clone.id)
  end

  def edit
  end

  def confirm
    @clone = Clone.new(clone_params) # <=POSTされたパラメータを取得
  end


  def update
    if @clone.update(clone_params)
      redirect_to clones_path, notice:"ツイートを編集しました"
    else
      render 'edit'
    end
  end

  def create
    @clone = current_user.clones.new(clone_params)
    if @clone.save
      redirect_to clones_path, notice:"ツイートしました！"
    else
      render 'new'
    end
  end

  def destroy
    @clone.destroy
    redirect_to clones_path, notice:"ツイートを削除しました"
  end

  def favorite
    @favorite_clones = current_user.favorite_clones
  end


  def set_clone
    @clone = Clone.find(params[:id])
  end

  def logged_in_user
    unless logged_in?
      flash[:danger] = "ログインしてください"
      redirect_to new_session_path
    end
  end


  private
  def clone_params
    params.require(:clone).permit(:contents)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    favorite = current_user.favorites.create(clone_id: params[:clone_id])
    redirect_to clones_path,notice: "#{favorite.clone.user.name}さんのブログをお気に入りにしました"
  end

  def  destroy
    favorite = current_user.favorites.find_by(clone_id: params[:clone_id]).destroy
    redirect_to clones_path,notice: "#{favorite.clone.user.name}さんのブログをお気に入りを解除しました"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash[:danger] = 'ログインに失敗しました'
      render 'new'
    end
  end
  
  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    @user=  User.find(params[:id])

  end

  def create
     @user = User.new(user_params)
     if @user.save
       redirect_to user_path(@user.id),notice:'ログインしました！'
     else
       render 'new'
     end
  end

  

  private
   def user_params
     params.require(:user).permit(:name,:email,:password,:password_confirmation)
   end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clones_helper.rb
module ClonesHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_clones_path
    elsif action_name == 'edit'
      clone_path
    end
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !current_user.nil?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/clones/_form.html.erb
<%= form_for(@clone, url: choose_new_or_edit) do |f| %>
  <% if @clone.errors.any? %>
     <div id="error_explanation">
       <h2><%= pluralize(@clone.errors.count, "error") %> prohibited this article from being saved:</h2>

       <ul>
         <% @clone.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
         <% end %>
       </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :contents %><br>
    <%= f.text_area :contents %>
  </div>
  <div class="actions">
    <%=f.submit 'next!' %>
  </div>
    <% end %>
  

app/views/clones/confirm.html.erb
<h4>以下の内容で、送信する。</h4>

<%= form_for(@clone) do |f| %>
  <!-- `f.hidden_field`を使用して、リクエストパラメータに値を設定できるようにしています。 -->
  <%= f.hidden_field :contents  %>
  <!-- @blog.titleと@blog.contentとすることで、表示用の値を画面に出力しています。 -->
  <p>本文:<%= @clone.contents %></p>
  <%= f.submit "登録する" %>
<% end %>

app/views/clones/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-4 col-md-offset-4 form-content">
      <h2>ツイート編集画面</h2>

      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/clones/favorite.html.erb
<div class="container">
  <div class="row">

      <% @favorite_clones.each do |clone| %>
      <div class="favorite-panel col-xs-12 col-md-4 col-md-offset-4">

      <h2>🌟<%= clone.contents %></h2>
      <p><%= clone.created_at %></p>

        </div>
      <% end %>

  </div>
</div>

app/views/clones/index.html.erb
<div class="container">
  <article class-"tweet row">
      <% @clones.each do |clone| %>
        <div class-"blog-panel col-xs-12 col-md-4 col-md-offset-4">
          <h2><%= clone.contents %></h2>
          <p><%= clone.created_at %></p>

                    <% if clone.user_id == current_user.id %>
                      <%= link_to 'Show', clone_path(clone.id)  %> |
                      <%= link_to 'Edit', edit_clone_path(clone.id)%> |
                      <%= link_to 'Destroy', clone_path(clone.id),method: :delete, data: { confirm: 'Are you sure?' }%>
                    <% else %>
                      <%= link_to 'Show', clone_path(clone.id)  %> 
                    <% end %>

        </div>
      <% end %>
  </article>
</div>

app/views/clones/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-4 col-md-offset-4 form-content">
      <h2>ツイートする</h2>

      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/clones/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-4 col-md-offset-4 form-content">
      <h1>ツイート詳細</h1>

      <p>Contents: <%=@clone.contents%></p>

      <% unless @clone.user == current_user %>
        <% if @favorite.present? %>
          <%= link_to 'お気に入り解除する', favorite_path(clone_id: @clone.id), method: :delete, class: 'btn btn-danger' %>
        <% else %>
          <%= link_to 'お気に入りする', favorites_path(clone_id: @clone.id), method: :post, class: 'btn btn-prymary' %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwClone</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="bg-primary ">
      <ul>
        <li><%= link_to '#トップページ', clones_path %></li>
      </ul>
    </header>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
    <nav class="navbar navbar-default">
  　<div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#gnavi">
        <span class="sr-only"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand btn btn-primary" href="#">メニュー</a>
    </div>
    <div id="gnavi" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <% if logged_in? %>
          <li><%= link_to 'ツイート一覧📖', clones_path,class: 'btn btn-default'%></li>
          <li><%= link_to 'お気に入り一覧⭐️', favorite_clones_path,class: 'btn btn-default'%></li>
          <li><%= link_to 'つぶやく🖋', new_clone_path,class: 'btn btn-default' %></li>
          <li><%= link_to "プロフィール😃", user_path(current_user.id),class: 'btn btn-default'%></li>
          <li><%= link_to "ログアウト🚪",session_path(current_user.id), method: :delete,class: 'btn btn-default' %></li>
        <% else %>
          <li><%=link_to "登録📄", new_user_path,class: 'btn btn-default' %></li>
          <li><%=link_to "ログイン🔑", new_session_path ,class: 'btn btn-default'%></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

    <%= yield %>
    <footer class="bg-primary">
      <p>大課題１</p>
      <p>© 2015-2016 Copyright DIVE INTO CODE Corp.</p>
    </footer>

  </body>
</html>

app/views/users/new.html.erb
  <h1>Sign up</h1>
     <% if @user.errors.any? %>
       <div id="error_explanation">
         <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
         <ul>
           <% @user.errors.full_messages.each do |message| %>
             <li><%= message %></li>
           <% end %>
         </ul>
      </div>
     <% end %>

<div class="lodin_form">
<%= form_with(model: @user, local: true) do |f| %>  
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  
  <%= f.submit "Create my account" %>
<% end %>
</div>
 

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>

<p>メールアドレス: <%= @user.email %></p>